---
# tasks file for galaxyproject.pulsar

# Deploy a Pulsar server
#   http://pulsar.readthedocs.org/


# More copying from galaxy role:
# To my knowledge there is no other way to know whether or not the consumer of
# this role has set `become: true` outside this role, and `become: {{ foo |
# default(omit) }}` on a task/block actually clobbers the higher level use of
# `become`. This is a temporary solution.
- name: Set privilege separation default variables
  set_fact:
    __pulsar_remote_user: "{{ ansible_user | default(omit) }}"
    __pulsar_become: "{{ ansible_env.SUDO_USER is defined }}"
    __pulsar_become_user: "{{ ansible_user_id | default(omit) }}"

- name: Include virtualenv setup tasks
  import_tasks: virtualenv.yml

- name: Create/update virtualenv
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv_command: "{{ pulsar_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ pulsar_virtualenv_python | default(omit) }}"
  environment:
    VIRTUAL_ENV: "{{ pulsar_venv_dir }}"
  with_items:
    - pip
    - setuptools
  when: pulsar_pip_install == true

- name: Install Pulsar (git+pip)
  pip:
    name: "{{ 'git+' ~ pulsar_git_repo ~ '@' ~ pulsar_changeset_id ~ '#egg=pulsar-app' }}"
    editable: false
    state: forcereinstall
  when: pulsar_pip_install == true and pulsar_changeset_id is defined

- name: Install Pulsar (pip)
  pip:
    name: pulsar-app
    state: latest
    virtualenv: "{{ pulsar_venv_dir }}"
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv_command: "{{ pulsar_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ pulsar_virtualenv_python | default(omit) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: pulsar_pip_install == true and pulsar_changeset_id is not defined

- name: Install Pulsar (source)
  git: dest={{ pulsar_server_dir }} force=no repo={{ pulsar_git_repo }} version={{ pulsar_changeset_id | default('master') }} executable={{ git_executable | default(omit) }}
  when: pulsar_pip_install == false

- name: Install Pulsar base dependencies for source install
  pip:
    requirements: "{{ pulsar_server_dir }}/requirements.txt"
    virtualenv: "{{ pulsar_venv_dir }}"
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv_command: "{{ pulsar_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ pulsar_virtualenv_python | default(omit) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: pulsar_pip_install == false

- name: Install Pulsar dependencies (optional)
  pip:
    name: "{{ item }}"
    virtualenv: "{{ pulsar_venv_dir }}"
    extra_args: "{{ pip_extra_args | default('') }}"
    virtualenv_command: "{{ pulsar_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv_python: "{{ pulsar_virtualenv_python | default(omit) }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  #environment: "{{ pulsar_install_environments[item.split('=')[0]] if item.split('=')[0] in pulsar_install_environments else {} }}"
  with_items: "{{ pulsar_optional_dependencies }}"

- name: Create Pulsar config dir
  file: state=directory path={{ pulsar_config_dir }}

- name: Create Pulsar app configuration file
  template: src=app.yml.j2 dest={{ pulsar_config_dir }}/app.yml mode=0444 backup=yes
  when: pulsar_yaml_config is defined

- name: Create Pulsar job manager configuration file
  template: src=job_managers.ini.j2 dest={{ pulsar_job_managers_config }} mode=0444 backup=yes
  when: pulsar_job_managers is defined

- name: Create additional Pulsar config files
  template: src={{ item }}.j2 dest={{ pulsar_config_dir }}/{{ item }} mode=0444 backup=yes
  with_items:
    - server.ini
    - local_env.sh
    - job_metrics_conf.xml
    - dependency_resolvers_conf.xml

- include_tasks: systemd.yml
  when: pulsar_systemd
